# Site settings
baseURL: "https://angel-crawford.de/"
theme: "card"
disableKinds: ["section", "taxonomy", "term", "RSS"]
copyright: "Angel Crawford"
enableRobotsTXT: true
author: "Angel Crawford"
twitterHandle: "crawford_ftw" #Twitter name, to bind shared cards to your profile
# Enter your tracking code to enable Google Analytics
#googleAnalytics = ""
defaultContentLanguage: en

markup:
  goldmark:
    renderer:
      unsafe: true

imaging:
  quality: 100

params:
  breakpoints:
    bp_smallish: "1200px"
    bp_tablet  : "800px"
    bp_mobile  : "500px"
  birthdate       : "1987-02-05"
  shareImage      : "images/social.jpg"
  favicon         : "favicon.ico"
  profile         : "images/profile.jpg"
  linkCounter : 10 # WICHTIG! Mobile circle not working, if not set
  links:
    - text    : "Mastodon"
      url     : "https://norden.social/@Angel_Crawford_ftw"
      icon    : "ri-mastodon-fill"
      color   : "#6364FF"
      opacity : "0.9"
    - text    : "Instagram"
      url     : "https://www.instagram.com/angel_crawford_ftw"
      icon    : "ri-instagram-line"
      color   : "#c13584"
    - text    : "Threads"
      url     : "https://www.threads.net/@angel_crawford_ftw"
      icon    : "ri-threads-line"
      color   : "#ffffff"
      opacity : "0.6"
    - text    : "Facebook"
      url     : "https://www.facebook.com/angel.crawford.ftw"
      icon    : "ri-facebook-circle-line"
      color   : "#4267B2"
    - text    : "Spotify"
      url     : "https://open.spotify.com/user/l73ksvrl7vnidevukda1z0kwj"
      icon    : "ri-spotify-line"
      color   : "#1DB954"
      opacity : "0.8"
    - text    : "Reddit"
      url     : "https://www.reddit.com/user/Angel_Crawford"
      icon    : "ri-reddit-line"
      color   : "#FF5700"
      opacity : "0.6"
    - text    : "EA ID"
      url     : "https://www.ea.com/games/the-sims/the-sims-4/pc/gallery/browse?category=all&searchtype=ea_origin_id&searchquery=Angel_Noidat&maxis=false"
      icon    : "ri-gamepad-line"
      color   : "#a6e329"
      opacity : "0.5"
    - text    : "Github"
      url     : "https://github.com/AngelCrawford"
      icon    : "ri-github-line"
      color   : "#555"
    - text    : "CodePen"
      url     : "https://codepen.io/angel_crawford"
      icon    : "ri-codepen-fill"
      color   : "#888"
    - text    : "Stack Overflow"
      url     : "https://stackoverflow.com/u/3206211"
      icon    : "ri-stack-overflow-line"
      color   : "#f48024"
      opacity : "0.8"

languages:
  en:
    languageCode : en-US
    languageName : English
    title        : "Angel Crawford | Profile Card"
    weight       : 1
    params:
      description     : "Webcard (Short Profile) for Angel Crawford. Developer. Sun lover. Goth."
      keywords        : "Webcard, Profile Card, Angel Crawford"
      flag_file       : "images/en.png"
      flag_title      : "Change the Language to"
    menu:
      footer:
        - name       : "Legal Notice"
          identifier : "legal-notice"
          url        : "legal-notice/"
          weight     : 1
        - name       : "Privacy Policy"
          identifier : "privacy-policy"
          url        : "privacy-policy/"
          weight     : 0
  de:
    languageCode : de-DE
    languageName : Deutsch
    title        : "Angel Crawford | Profil Karte"
    weight       : 2
    params:
      description     : "Webcard (Kurzprofil) für Angel Crawford. Entwickler. Sonnenliebhaber. Goth."
      keywords        : "Webcard, Profil Karte, Angel Crawford"
      flag_file       : "images/de.png"
      flag_title      : "Ändere die Sprache zu"
    menu:
      footer:
        - name       : "Impressum"
          identifier : "legal-notice"
          url        : "impressum/"
          weight     : 1
        - name       : "Datenschutz"
          identifier : "datenschutz"
          url        : "datenschutz/"
          weight     : 0
