# Site settings
baseURL = "https://angel-crawford.de/"
theme = "card"
disableKinds = ["section", "taxonomy", "RSS"]
copyright = "Angel Crawford"
enableRobotsTXT = true
author = "Angel Crawford"
twitterHandle = "crawford_ftw" #Twitter name, to bind shared cards to your profile
# Enter your tracking code to enable Google Analytics
#googleAnalytics = ""

[sitemap]
  ChangeFreq = "weekly"
  Priority = "0.9"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
    [caches.images]
        dir    = ':cacheDir/:project'
        maxAge = "800h" # or some high value

[languages.en.params.breakpoints]
  bp_smallish = "1200px"
  bp_tablet = "800px"
  bp_mobile = "500px"
[languages.de.params.breakpoints]
  bp_smallish = "1200px"
  bp_tablet = "800px"
  bp_mobile = "500px"
