# Site settings
baseURL: "https://angel-crawford.de/"
theme: "card"
disableKinds: ["section", "taxonomy", "term", "RSS"]
copyright: "Angel Crawford"
enableRobotsTXT: true
author: "Angel Crawford"
twitterHandle: "crawford_ftw" #Twitter name, to bind shared cards to your profile
# Enter your tracking code to enable Google Analytics
#googleAnalytics = ""
defaultContentLanguage: en

sitemap:
  ChangeFreq: "weekly"
  Priority: "0.9"

markup:
  goldmark:
    renderer:
      unsafe: true

caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: "800h"
  images:
    dir: :resourceDir/_gen
    maxAge: "800h"

resources:
  - src: "images/slider/01.webp"
    params:
      weight   : 20
      credit   : "📅 2021-10-02 <small>|</small> 📷 Me <small>|</small> 💄 Me"
      position : "center"
  - src: "images/slider/background_6.webp"
    params:
      weight   : 10
      credit   : "📅 2020-08-01 <small>|</small> 📷 <a href='https://www.facebook.com/BrainfoodPhotographyDesign'>Brainfood Photography & Layout</a> <small>|</small> 💄 Costume by me ;)"
      position : "center"

params:
  breakpoints:
    bp_smallish: "1200px"
    bp_tablet  : "800px"
    bp_mobile  : "500px"
  birthdate       : "1987-02-05"
  spotifyPlaylist : "https://open.spotify.com/embed/playlist/520act29dQq3SDNilMbpfd"
  shareImage      : "images/social.jpg"
  favicon         : "favicon.ico"
  visual:
    image:
        size     : "cover"
        position : "50% 10%"
        count    : 9 # wird für das CSS benötigt!
        clickSpeed    : "1s"
        file:
          - url          : "images/slider/background_5.webp"
            credit       : "📅 2021-10-02 <small>|</small> 📷 Me <small>|</small> 💄 Me"
            position     : "center"
          - url          : "images/slider/background_9.webp"
            credit       : "📅 2022-09-22 <small>|</small> 📷 Me <small>|</small> 💄 Me"
            position     : "center"
          - url          : "images/slider/background10.webp"
            credit       : "📅 2023-05-28 <small>|</small> 📷 Me <small>|</small> 💄 Me"
            position     : "top center"
          - url          : "images/slider/background_2.webp"
            credit       : "📅 2013-05-14 <small>|</small> 📷 <a href='https://www.facebook.com/lichtundschattenspiel'>Licht- und Schattenspiel</a> <small>|</small> 💄 Me"
          - url          : "images/slider/background_1.webp"
            credit       : "📅 2015-01-11 <small>|</small> 📷 <a href='https://www.facebook.com/lichtundschattenspiel'>Licht- und Schattenspiel</a> <small>|</small> 💄 <a href='https://www.facebook.com/KaraKuckoo'>Kara Kuckoo</a>"
          - url          : "images/slider/background_3.webp"
            credit       : "📅 2015-01-11 <small>|</small> 📷 <a href='https://www.facebook.com/lichtundschattenspiel'>Licht- und Schattenspiel</a> <small>|</small> 💄 <a href='https://www.facebook.com/KaraKuckoo'>Kara Kuckoo</a>"
          - url          : "images/slider/background_6.webp"
            credit       : "📅 2020-08-01 <small>|</small> 📷 <a href='https://www.facebook.com/BrainfoodPhotographyDesign'>Brainfood Photography & Layout</a> <small>|</small> 💄 Costume by me ;)"
          - url          : "images/slider/background_4.webp"
            credit       : "📅 2019-09-28 <small>|</small> 📷 Me <small>|</small> 💄 Me"
          - url          : "images/slider/background11.webp"
            credit       : "📅 2023-08-12 <small>|</small> 📷 <a href='https://www.instagram.com/adjastonascursol'>Adjaston Ascursol</a> <small>|</small> 💄 Me"
            position     : "top center"
  links:
    - text    : "Instagram"
      url     : "https://www.instagram.com/angel_crawford_ftw"
      icon    : "ri-instagram-line"
      color   : "#c13584"
    - text    : "Threads"
      url     : "https://www.threads.net/@angel_crawford_ftw"
      icon    : "ri-threads-line"
      color   : "#ffffff"
      opacity : "0.6"
    - text    : "Facebook"
      url     : "https://www.facebook.com/angel.crawford.ftw"
      icon    : "ri-facebook-circle-line"
      color   : "#4267B2"
    - text    : "Spotify"
      url     : "https://open.spotify.com/user/l73ksvrl7vnidevukda1z0kwj"
      icon    : "ri-spotify-line"
      color   : "#1DB954"
      opacity : "0.8"
    - text    : "Reddit"
      url     : "https://www.reddit.com/user/Angel_Crawford"
      icon    : "ri-reddit-line"
      color   : "#FF5700"
      opacity : "0.6"
    - text    : "EA ID"
      url     : "https://www.ea.com/games/the-sims/the-sims-4/pc/gallery/browse?category=all&searchtype=ea_origin_id&searchquery=Angel_Noidat&maxis=false"
      icon    : "ri-gamepad-line"
      color   : "#a6e329"
      opacity : "0.5"
    - text    : "Github"
      url     : "https://github.com/AngelCrawford"
      icon    : "ri-github-line"
      color   : "#555"
    - text    : "CodePen"
      url     : "https://codepen.io/angel_crawford"
      icon    : "ri-codepen-fill"
      color   : "#888"
    - text    : "Stack Overflow"
      url     : "https://stackoverflow.com/u/3206211"
      icon    : "ri-stack-overflow-line"
      color   : "#f48024"
      opacity : "0.8"

languages:
  en:
    languageCode : en-US
    languageName : English
    title        : "Angel Crawford | Profile Card"
    weight       : 1
    params:
      description     : "Webcard (Short Profile) for Angel Crawford. Developer. Sun lover. Goth."
      keywords        : "Webcard, Profile Card, Angel Crawford"
      flag_file       : "images/en.png"
      flag_title      : "Change the Language to"
    menu:
      footer:
        - name       : "Legal Notice"
          identifier : "legal-notice"
          url        : "legal-notice/"
          weight     : 1
        - name       : "Privacy Policy"
          identifier : "privacy-policy"
          url        : "privacy-policy/"
          weight     : 0
  de:
    languageCode : de-DE
    languageName : Deutsch
    title        : "Angel Crawford | Profil Karte"
    weight       : 2
    params:
      description     : "Webcard (Kurzprofil) für Angel Crawford. Entwickler. Sonnenliebhaber. Goth."
      keywords        : "Webcard, Profil Karte, Angel Crawford"
      flag_file       : "images/de.png"
      flag_title      : "Ändere die Sprache zu"
    menu:
      footer:
        - name       : "Impressum"
          identifier : "legal-notice"
          url        : "impressum/"
          weight     : 1
        - name       : "Datenschutz"
          identifier : "datenschutz"
          url        : "datenschutz/"
          weight     : 0

