[[footer]]
  identifier = "legal-notice"
  name       = "Legal Notice"
  url        = "legal-notice/"
  weight     = 1
[[footer]]
  identifie  = "privacy-policy"
  name       = "Privacy Policy"
  url        = "privacy-policy/"
  weight     = 0
